
version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    filename: log/alcp.log
    maxBytes: 1048576
    backupCount: 5
    formatter: detailed
    level: DEBUG

root:
  level: DEBUG
  handlers: [console, file]
